amcl:
  ros__parameters:
    use_sim_time: true
    map_type: occupancy
    scan_topic: scan
    base_frame_id: base_footprint
    odom_frame_id: odom
    min_particles: 500
    max_particles: 2001
    transform_tolerance: 0.1
    laser_model_type: likelihood_field
    update_min_d: 0.2
    update_min_a: 0.2

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.2
      lookahead_dist: 0.4

map_server:
  ros__parameters:
    yaml_filename: "/home/wodo/workspace/maps/map_candidat.yaml"
