slam_toolbox:
  ros__parameters:
  
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    use_map_saver: true
    mode: mapping #localization
    use_sim_time: true
