slam_toolbox:
  ros__parameters:
    use_sim_time: false
    resolution: 0.05
    max_laser_range: 20.0
    mode: "mapping"
    map_file_name: "./maps/map"  # Карта будет сохранена как maps/map.yaml
    minimum_time_between_update: 0.2
